#!/usr/bin/env python3
"""
generate_top.py - Automatic top-level generator for Papilio Wishbone Bus

Scans PlatformIO lib_deps for Wishbone peripherals and generates top.v
"""

import json
import os
import sys
from pathlib import Path

Import("env")

def find_wishbone_libraries(project_dir):
    """Find all Wishbone peripheral libraries in the project"""
    peripherals = []
    
    # Get lib_deps from platformio.ini
    lib_deps = env.GetProjectOption("lib_deps", [])
    
    print("Scanning for Wishbone peripherals...")
    print(f"lib_deps: {lib_deps}")
    
    # Check .pio/libdeps for installed libraries
    libdeps_dir = project_dir / ".pio" / "libdeps" / env["PIOENV"]
    
    if not libdeps_dir.exists():
        print(f"Warning: libdeps directory not found: {libdeps_dir}")
        return peripherals
    
    # Scan each library
    for lib_dir in libdeps_dir.iterdir():
        if not lib_dir.is_dir():
            continue
            
        # Look for library.json
        lib_json = lib_dir / "library.json"
        if not lib_json.exists():
            continue
        
        try:
            with open(lib_json, 'r') as f:
                lib_data = json.load(f)
            
            # Check if it's a Wishbone peripheral
            if 'wishbone' in lib_data.get('keywords', []):
                # Look for wishbone_peripheral.json with peripheral metadata
                peripheral_json = lib_dir / "wishbone_peripheral.json"
                
                if peripheral_json.exists():
                    with open(peripheral_json, 'r') as f:
                        peripheral_data = json.load(f)
                    
                    peripheral_data['lib_path'] = str(lib_dir)
                    peripherals.append(peripheral_data)
                    
                    print(f"Found Wishbone peripheral: {peripheral_data['name']}")
        
        except Exception as e:
            print(f"Warning: Error reading {lib_json}: {e}")
    
    return peripherals

def generate_top_v(peripherals, output_path):
    """Generate top.v from peripherals"""
    
    # Calculate total slots needed
    total_slots = 1  # Slot 0 is memory map
    for periph in peripherals:
        total_slots += periph.get('slots_required', 1)
    
    if total_slots > 32:
        print(f"ERROR: Too many slots ({total_slots}). Maximum is 32.")
        sys.exit(1)
    
    # Build device ID and SPI bits arrays
    device_ids = ['`PWB_DEVID_SYSTEM']  # Slot 0
    spi_bits = ['`PWB_SPI_WIDTH_32']     # Slot 0 uses 32-bit
    
    current_slot = 1
    peripheral_instances = []
    peripheral_wires = []
    peripheral_acks = ['map_ack']
    peripheral_data = ['slot_sel[0] ? map_dat : ']
    
    for periph in peripherals:
        name = periph['name']
        module = periph['module_name']
        device_id = periph['device_id']
        spi_width = periph.get('spi_transfer_bits', 8)
        num_slots = periph.get('slots_required', 1)
        
        # Add to arrays
        for i in range(num_slots):
            slot_num = current_slot + i
            device_ids.append(f"16'h{device_id:04X}")
            spi_bits.append(f"6'd{spi_width}")
        
        # Generate instance
        inst_name = periph.get('instance_name', name.lower().replace('-', '_'))
        
        # Generate port connections
        ports = f"""    .clk(clk),
    .rst(rst),
    .wb_adr_i(wb_adr[7:0]),
    .wb_dat_i(wb_dat_m2s),
    .wb_dat_o({inst_name}_dat),
    .wb_stb_i(slot_sel[{current_slot}]),
    .wb_we_i(wb_we),
    .wb_ack_o({inst_name}_ack)"""
        
        # Add peripheral-specific ports if defined
        if 'ports' in periph:
            for port in periph['ports']:
                ports += f",\n    .{port['name']}({port['connection']})"
        
        instance = f"""// {name} (Slot {current_slot})
{module} #(
    .SLOT_NUMBER({current_slot}),
    .DEVICE_ID(16'h{device_id:04X}),
    .SPI_TRANSFER_BITS({spi_width})
) {inst_name} (
{ports}
);"""
        
        peripheral_instances.append(instance)
        peripheral_acks.append(f"{inst_name}_ack")
        peripheral_data.append(f"slot_sel[{current_slot}] ? {inst_name}_dat : ")
        peripheral_wires.append(f"wire [31:0] {inst_name}_dat;")
        peripheral_wires.append(f"wire {inst_name}_ack;")
        
        current_slot += num_slots
    
    # Pad remaining slots with EMPTY
    for i in range(current_slot, 32):
        device_ids.append('`PWB_DEVID_EMPTY')
        spi_bits.append('`PWB_SPI_WIDTH_8')
    
    # Generate top.v
    top_v = f'''// top.v - Auto-generated by generate_top.py
// DO NOT EDIT - This file is automatically generated

`include "pwb_pkg.vh"

module top (
    input wire clk,
    input wire rst,
    
    // SPI from ESP32
    input wire esp_sclk,
    input wire esp_mosi,
    output wire esp_miso,
    input wire esp_cs_n,
    
    // Peripheral I/O
    output wire [23:0] rgb_led
    // Add other peripheral I/O as needed
);

// =============================================================================
// Wishbone Bus
// =============================================================================

wire [23:0] wb_adr;
wire [31:0] wb_dat_m2s;  // Master to slave
wire [31:0] wb_dat_s2m;  // Slave to master
wire wb_cyc, wb_stb, wb_we, wb_ack;

// =============================================================================
// Peripheral Configuration
// =============================================================================

localparam NUM_SLOTS = {total_slots};

localparam [15:0] DEVICE_IDS [0:31] = '{{
    {', '.join(device_ids)}
}};

localparam [5:0] SPI_BITS [0:31] = '{{
    {', '.join(spi_bits)}
}};

// =============================================================================
// SPI Bridge
// =============================================================================

pwb_spi_bridge #(
    .SLOT_SPI_BITS(SPI_BITS)
) bridge (
    .clk(clk),
    .rst(rst),
    .spi_sclk(esp_sclk),
    .spi_mosi(esp_mosi),
    .spi_miso(esp_miso),
    .spi_cs_n(esp_cs_n),
    .wb_adr_o(wb_adr),
    .wb_dat_o(wb_dat_m2s),
    .wb_dat_i(wb_dat_s2m),
    .wb_cyc_o(wb_cyc),
    .wb_stb_o(wb_stb),
    .wb_we_o(wb_we),
    .wb_ack_i(wb_ack)
);

// =============================================================================
// Slot Decoder
// =============================================================================

wire [31:0] slot_sel;

// Simple one-hot decoder
assign slot_sel = (wb_adr[12:8] < 32) ? (1 << wb_adr[12:8]) : 32'h0;

// =============================================================================
// Memory Map (Slot 0)
// =============================================================================

wire [31:0] map_dat;
wire map_ack;

pwb_memory_map #(
    .NUM_SLOTS(NUM_SLOTS),
    .SLOT_DEVICE_IDS(DEVICE_IDS),
    .SLOT_SPI_BITS(SPI_BITS)
) memory_map (
    .clk(clk),
    .rst(rst),
    .wb_adr_i(wb_adr[7:0]),
    .wb_dat_i(wb_dat_m2s),
    .wb_dat_o(map_dat),
    .wb_stb_i(slot_sel[0]),
    .wb_we_i(wb_we),
    .wb_ack_o(map_ack)
);

// =============================================================================
// Peripherals
// =============================================================================

{chr(10).join(peripheral_wires)}

{chr(10) + chr(10).join(peripheral_instances)}

// =============================================================================
// Wishbone Interconnect
// =============================================================================

// Combine ACKs
assign wb_ack = {' | '.join(peripheral_acks)};

// Combine read data
assign wb_dat_s2m = {' '.join(peripheral_data)}32'hFFFFFFFF;

endmodule
'''
    
    # Write to file
    with open(output_path, 'w') as f:
        f.write(top_v)
    
    print(f"Generated {output_path} with {total_slots} slots")
    print(f"Peripherals: {[p['name'] for p in peripherals]}")

# Main execution
def main():
    project_dir = Path(env["PROJECT_DIR"])
    
    # Find all Wishbone peripherals
    peripherals = find_wishbone_libraries(project_dir)
    
    if not peripherals:
        print("Warning: No Wishbone peripherals found")
        # Generate minimal top.v with just memory map
        peripherals = []
    
    # Generate top.v in src/gateware
    output_dir = project_dir / "src" / "gateware"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "top.v"
    
    generate_top_v(peripherals, output_path)
    
    print(f"Top-level generation complete!")

# Run during pre-build
main()
