// gowin_rpll_50_250.v
// Gowin rPLL: 50MHz input -> 250MHz output
// For TMDS serialization (5x pixel clock)
// Generated by Gowin IDE, parameters validated
//
// Input: 50 MHz (pixel clock from first PLL)
// Output: 250 MHz (TMDS serial clock = 5x pixel clock)
// 
// Calculation with IDIV=0, FBDIV=4, ODIV=2:
//   PFD = 50 / 1 = 50 MHz ✓
//   CLKOUT = 50 * 5 / 1 = 250 MHz
//   VCO = 50 * 5 * 2 / 1 = 500 MHz (at minimum, but valid ✓)

module gowin_rpll_50_250 (
    input clkin,    // 50 MHz input (from first PLL)
    output clkout,  // 250 MHz output (5x pixel clock for TMDS)
    output lock     // PLL lock indicator
);

    wire clkoutp_o;
    wire clkoutd_o;
    wire clkoutd3_o;
    wire gw_gnd;
    
    assign gw_gnd = 1'b0;

    rPLL #(
        .FCLKIN("50"),          // Input frequency: 50 MHz (from first PLL)
        .DYN_IDIV_SEL("false"),
        .IDIV_SEL(0),           // Input divider: 1 -> PFD = 50 MHz
        .DYN_FBDIV_SEL("false"),
        .FBDIV_SEL(4),          // Feedback divider: 5 -> CLKOUT = 250 MHz
        .DYN_ODIV_SEL("false"),
        .ODIV_SEL(2),           // Output divider: 2 -> VCO = 500 MHz
        .PSDA_SEL("0000"),
        .DYN_DA_EN("false"),
        .DUTYDA_SEL("1000"),
        .CLKOUT_FT_DIR(1'b1),
        .CLKOUTP_FT_DIR(1'b1),
        .CLKOUT_DLY_STEP(0),
        .CLKOUTP_DLY_STEP(0),
        .CLKFB_SEL("internal"),
        .CLKOUT_BYPASS("false"),
        .CLKOUTP_BYPASS("false"),
        .CLKOUTD_BYPASS("false"),
        .DYN_SDIV_SEL(2),
        .CLKOUTD_SRC("CLKOUT"),
        .CLKOUTD3_SRC("CLKOUT"),
        .DEVICE("GW2A-18C")
    ) rpll_inst (
        .CLKOUT(clkout),
        .LOCK(lock),
        .CLKOUTP(clkoutp_o),
        .CLKOUTD(clkoutd_o),
        .CLKOUTD3(clkoutd3_o),
        .RESET(gw_gnd),
        .RESET_P(gw_gnd),
        .CLKIN(clkin),
        .CLKFB(gw_gnd),
        .FBDSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .IDSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .ODSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .PSDA({gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .DUTYDA({gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .FDLY({gw_gnd,gw_gnd,gw_gnd,gw_gnd})
    );

endmodule
