// gowin_rpll_27_50.v
// Gowin rPLL: 27MHz input -> 50.14MHz output
// For HQVGA VGA timing (800x600@72Hz needs 50MHz)
// Generated by Gowin IDE, parameters validated
//
// Input: 27 MHz
// Output: 50.14 MHz pixel clock
// 
// Calculation with IDIV=6, FBDIV=12, ODIV=16:
//   PFD = 27 / 7 = 3.86 MHz ✓
//   CLKOUT = 27 * 13 / 7 = 50.14 MHz
//   VCO = 27 * 13 * 16 / 7 = 802.3 MHz (within 500-1250 range ✓)

module gowin_rpll_27_50 (
    input clkin,    // 27 MHz input
    output clkout,  // 51 MHz output (pixel clock)
    output lock     // PLL lock indicator
);

    wire clkoutp_o;
    wire clkoutd_o;
    wire clkoutd3_o;
    wire gw_gnd;
    
    assign gw_gnd = 1'b0;

    rPLL #(
        .FCLKIN("27"),          // Input frequency: 27 MHz
        .DYN_IDIV_SEL("false"),
        .IDIV_SEL(6),           // Input divider: 7 (IDIV = IDIV_SEL + 1) -> PFD = 3.86 MHz
        .DYN_FBDIV_SEL("false"),
        .FBDIV_SEL(12),         // Feedback divider: 13 -> CLKOUT = 50.14 MHz
        .DYN_ODIV_SEL("false"),
        .ODIV_SEL(16),          // Output divider: 16 -> VCO = 802.3 MHz
        .PSDA_SEL("0000"),
        .DYN_DA_EN("false"),
        .DUTYDA_SEL("1000"),
        .CLKOUT_FT_DIR(1'b1),
        .CLKOUTP_FT_DIR(1'b1),
        .CLKOUT_DLY_STEP(0),
        .CLKOUTP_DLY_STEP(0),
        .CLKFB_SEL("internal"),
        .CLKOUT_BYPASS("false"),
        .CLKOUTP_BYPASS("false"),
        .CLKOUTD_BYPASS("false"),
        .DYN_SDIV_SEL(2),
        .CLKOUTD_SRC("CLKOUT"),
        .CLKOUTD3_SRC("CLKOUT"),
        .DEVICE("GW2A-18C")
    ) rpll_inst (
        .CLKOUT(clkout),
        .LOCK(lock),
        .CLKOUTP(clkoutp_o),
        .CLKOUTD(clkoutd_o),
        .CLKOUTD3(clkoutd3_o),
        .RESET(gw_gnd),
        .RESET_P(gw_gnd),
        .CLKIN(clkin),
        .CLKFB(gw_gnd),
        .FBDSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .IDSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .ODSEL({gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .PSDA({gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .DUTYDA({gw_gnd,gw_gnd,gw_gnd,gw_gnd}),
        .FDLY({gw_gnd,gw_gnd,gw_gnd,gw_gnd})
    );

endmodule
